; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
; 乐鑫国内镜像，强制走国内下载
platform_packages =
  framework-arduinoespressif32@https://dl.espressif.cn/github_assets/espressif/arduino-esp32/releases/download/2.0.17/esp32-2.0.17.zip

